/*"Pending": [
    "Languages",
    "Music",
    "Pets",
    "Search",
    "Spotify",
    "Apple Vision Pro",
    "Newsletters",
    "SEO",
    "Android",
    "Dating",
    "Computers",
    "Games",
    "Linux",
    "Mac",
    "iOS",
    "Robots",
    "Storage",
    "Windows",
    "Video",
    "Apple",
    "Construction",
    "Delivery",
    "GitHub",
    "Physics",
    "Science",
    "Tech",
    "Writing",
    "Wallpaper",
  ],*/

export const topicsTree = {
  "Arts & Culture": {
    "Visual Arts": {
      "Painting": {},
      "Photography": {},
      "Digital Art": {},
      "Drawing": {},
      "Art": {},
      "Illustration": {},
      "Video Art": {},
    },
    "Performing Arts": {
      "Theater": {},
      "Concert": {},
      "Concerts": {},
      "Live Music": {},
      "Opera": {},
      "Sporting Events": {},
      "Live Events": {},
    },
    "Literature": {
      "Books": {},
      "Art Books": {},
      "Fashion Books": {},
      "History Books": {},
      "Horror Books": {},
      "Thriller Books": {},
      "Novels": {},
      "Textbooks": {},
      "Coding Books": {},
      "Business Books": {},
      "Design Books": {},
      "Science Books": {},
      "Crime Books": {},
      "Adult Coloring Books": {},
      "Yoga Books": {},
    },
  },
  "Business & Entrepreneurship": {
    "Business Operations": {
      "Business": {},
      "Business Intelligence": {},
      "Business Travel": {},
      "Change Management": {},
      "Consulting": {},
      "Customer Communication": {},
      "Customer Success": {},
      "Operations": {},
      "Hiring": {},
      "Human Resources": {},
      "Monetization": {},
      "Public Relations": {},
    },
    "Marketing & Advertising": {
      "Marketing": {},
      "Advertising": {},
      "Affiliate marketing": {},
      "Branding": {},
      "Email Marketing": {},
      "Event marketing": {},
      "Growth Hacking": {},
      "Growth Hacks": {},
      "Influencer marketing": {},
      "Marketing attribution": {},
      "Marketing automation": {},
      "Marketing calendar": {},
      "Social media marketing": {},
    },
    "Entrepreneurship": {
      "Startup Books": {},
      "Startup Lessons": {},
      "Crowdfunding": {},
      "Fundraising": {},
      "Product Hunt": {},
      "Side Project": {},
      "Venture Capital": {},
    },
  },
  "Computing & Technology": {
    "Software": {
      "Software Engineering": {},
      "Development": {},
      "Development Language": {},
      "Open Source": {},
      "API": {},
      "SDK": {},
      "Bots": {},
      "Productivity": {},
      "Wireframing": {},
      "Prototyping": {},
      "Developer Tools": {},
    },
    "Web Technology": {
      "Web App": {},
      "Web Design": {},
      "Website Builder": {},
      "Browser Extensions": {},
      "Chrome Extensions": {},
      "Edge Extensions": {},
      "Safari Extensions": {},
      "WordPress": {},
    },
    "Data & Analytics": {
      "Data": {},
      "Database": {},
      "Data Science": {},
      "Data Visualization": {},
      "Analytics": {},
      "Statistical Analysis": {},
    },
    "Hardware": {
      "3D Printer": {},
      "Accessories": {},
      "Appliances": {},
      "Batteries": {},
      "Custom Keyboards": {},
      "Drones": {},
      "DSLRs": {},
      "eBook Reader": {},
      "Gear VR": {},
      "Hardware": {},
      "HTC Vive": {},
      "Oculus Rift": {},
      "PC": {},
      "Playstation": {},
      "PlayStation VR": {},
      "Sensors": {},
      "Tablet": {},
      "Video cameras": {},
      "Vita": {},
      "Webcam": {},
      "Wearables": {},
    },
    "Security & Privacy": {
      "Ad Blockers": {},
      "Encryption": {},
      "Hacking": {},
      "Privacy": {},
      "Security": {},
      "VPN": {},
    },
    "Emerging Technologies": {
      "Artificial Intelligence": {},
      "Augmented Reality": {},
      "ARKit": {},
      "Blockchain": {},
      "Bitcoin": {},
      "Crypto": {},
      "Cryptocurrency": {},
      "DAO": {},
      "DApp": {},
      "DeFi": {},
      "Ethereum": {},
      "Extended Reality": {},
      "Internet of Things": {},
      "Mixed Reality": {},
      "NFT": {},
      "Virtual Assistants": {},
      "Virtual Reality": {},
      "Web3": {},
    },
  },
  "Design & Creative Work": {
    "Design": {
      "Design": {},
      "Design resources": {},
      "Design templates": {},
      "Design Tools": {},
      "Graphic Design": {},
      "Graphics": {},
      "Icons": {},
      "Illustration": {},
      "Logo Design": {},
      "Typography": {},
      "User Experience": {},
      "UX Design": {},
    },
    "Creative Work": {
      "Animation": {},
      "Calligraphy": {},
      "Crafting": {},
      "Crafting Games": {},
      "DIY": {},
      "DJing": {},
      "Drawing": {},
      "Maker Tools": {},
      "Modeling": {},
      "Painting": {},
      "Sketch": {},
      "Video Art": {},
    },
  },
  "Education & Careers": {
    "Education": {
      "Coding Books": {},
      "College Sports": {},
      "Education": {},
      "Online Learning": {},
      "School": {},
      "Textbooks": {},
    },
    "Careers": {
      "Career": {},
      "Freelance": {},
      "Legal": {},
      "Remote Work": {},
    },
  },
  "Finance & Money": {
    "Finance": {
      "Accounting": {},
      "Banking": {},
      "Budgeting": {},
      "Credit card": {},
      "CRM": {},
      "Finance": {},
      "Fintech": {},
      "Investing": {},
      "Money": {},
      "Payments": {},
      "Personal Finance": {},
      "SaaS": {},
      "Sales": {},
    },
    "Cryptocurrency": {
      "Bitcoin": {},
      "Blockchain": {},
      "Crypto": {},
      "Cryptocurrency": {},
      "DAO": {},
      "DApp": {},
      "DeFi": {},
      "Ethereum": {},
      "NFT": {},
    },
  },
  "Food & Beverages": {
    "Food": {
      "Cookbooks": {},
      "Cooking": {},
      "Dining": {},
      "Food Delivery": {},
      "Nutrition": {},
    },
    "Beverages": {
      "Alcohol": {},
      "Coffee": {},
      "Wine": {},
    },
  },
  "Games & Entertainment": {
    "Video Games": {
      "Action Games": {},
      "Adventure Games": {},
      "Crafting Games": {},
      "Driving Games": {},
      "Fantasy Games": {},
      "Fighting Games": {},
      "First Person Shooter": {},
      "Free Games": {},
      "Funny Games": {},
      "Historical Games": {},
      "Horror Games": {},
      "Indie Games": {},
      "Isometric Games": {},
      "MMOs": {},
      "Open World Games": {},
      "Platformers": {},
      "Pokemon": {},
      "Puzzle Games": {},
      "Retro Games": {},
      "RPGs": {},
      "Simulation Games": {},
      "Sports Games": {},
      "Strategy Games": {},
      "Tower Defense Games": {},
      "Word Games": {},
      "Zombie Games": {},
    },
    "Board & Card Games": {
      "Board Games": {},
      "Card Games": {},
      "Tabletop Games": {},
    },
    "Entertainment": {
      "Comedy": {},
      "DJ Khaled": {},
      "Drake": {},
      "Entertainment": {},
      "Funny": {},
      "GIFs": {},
      "Kanye West": {},
      "Memes": {},
      "Movies": {},
    },
    "Health & Fitness": {
      "Health": {
        "Health": {},
        "Health news": {},
        "Medical": {},
        "Meditation": {},
        "Pregnancy": {},
        "Psychedelics": {},
        "Quantified Self": {},
      },
      "Fitness": {
        "Fitness": {},
        "Biking": {},
        "Biohacking": {},
        "Boxing": {},
        "Climbing": {},
        "Hiking": {},
        "Running": {},
        "Skateboarding": {},
        "Surfing": {},
        "Swimming": {},
        "Weightlifting": {},
        "Yoga Books": {},
      },
    },
    "Home & Family": {
      "Home": {
        "Home": {},
        "Home Automation": {},
        "Home improvement": {},
        "Home office": {},
        "Home security": {},
        "Home services": {},
        "Home theater": {},
        "Interior design": {},
        "Furniture": {},
      },
      "Family": {
        "Babies": {},
        "Family": {},
        "Kids": {},
        "Parenting": {},
        "Pregnancy": {},
        "Toddlers": {},
      },
    },
    "Hobbies & Interests": {
      "Hobbies": {
        "Adult Coloring Books": {},
        "Aquarium": {},
        "Board Games": {},
        "Calligraphy": {},
        "Camping": {},
        "Card Games": {},
        "Coloring": {},
        "Crafting": {},
        "DIY": {},
        "DJing": {},
        "Drawing": {},
        "Gardening & Plants": {
          "Plants": {},
        },
        "Maker Tools": {},
        "Modeling": {},
        "Painting": {},
        "Puzzle Games": {},
        "Tabletop Games": {},
        "Word Games": {},
      },
      "Interests": {
        "Anonymous": {},
        "Cannabis": {},
        "Celebrities": {},
        "DJ Khaled": {},
        "Donald Trump": {},
        "Drake": {},
        "Kanye West": {},
        "Memes": {},
        "Military": {},
        "Nature": {},
        "Neighborhood": {},
        "Politics": {},
        "Pop culture": {},
        "Spirituality": {},
      },
    },
    "News & Media": {
      "News": {
        "News": {},
        "Local news": {},
        "Political news": {},
        "Tech news": {},
      },
      "Media": {
        "Blogs": {
          "Medium": {},
          "Product Hunt": {},
        },
        "Messaging": {
          "Email": {},
          "Chat rooms": {},
          "Facebook Messenger": {},
          "iMessage Apps": {},
          "Messaging": {},
          "Slack": {},
          "Snapchat": {},
          "Telegram": {},
        },
        "Multimedia": {
          "GIFs": {},
          "Memes": {},
          "Radio": {},
          "TV": {},
        },
        "Podcasts": {
          "Podcasts": {
            "SoundCloud": {},
          },
        },
        "Social Media": {
          "Anonymous": {},
          "Discord": {},
          "Instagram": {},
          "LinkedIn": {},
          "reddit": {},
          "Social Media": {},
          "Social Network": {},
          "Social Networking": {},
          "Twitter": {},
          "YouTube": {},
        },
        "Streaming": {
          "Streaming Services": {},
          "Video Streaming": {},
        },
      },
    },
    "Office & Productivity": {
      "Productivity": {
        "Notes": {
          "Notes": {},
          "Notion": {},
        },
        "Office Software": {
          "Menu Bar Apps": {},
          "Spreadsheets": {},
          "Text Editors": {},
          "Touch Bar Apps": {},
        },
        "Productivity": {
          "Alarms": {},
          "Bots": {},
          "Calendar": {},
          "Meetings": {},
          "Notifications": {},
          "Password manager": {},
          "Productivity": {},
          "Task Management": {},
          "Time Tracking": {},
        },
      },
      "Work Tools": {
        "Business Tools": {
          "CRM": {},
          "Customer Communication": {},
          "Customer Success": {},
          "Marketing": {},
          "Sales": {},
        },
        "Collaboration": {
          "File Sharing": {},
          "Meetings": {},
          "Project Management": {},
          "Slack": {},
          "Work In Progress": {},
        },
        "Office Setup": {
          "Home office": {},
          "Standing Desks": {},
        },
        "Work Trends": {
          "Digital Nomads": {
            "Global Nomad": {},
          },
          "Freelance": {},
          "Remote Work": {},
        },
      },
    },
    "Shopping": {
      "Fashion": {
        "Backpacks": {},
        "Clothing": {},
        "Fashion": {},
        "Fashion Books": {},
        "Jewelry": {},
        "Streetwear": {},
      },
      "Retail": {
        "Coupons": {},
        "Personal shopper": {},
        "Shopping": {},
      },
    },
    "Sports & Outdoors": {
      "Outdoors": {
        "Camping": {},
        "Climbing": {},
        "Gardening & Plants": {
          "Plants": {},
        },
        "Hiking": {},
        "Nature": {},
        "Outdoors": {},
        "Snow sports": {},
        "Survival": {},
        "Surfing": {},
      },
      "Sports": {
        "Baseball": {},
        "Basketball": {},
        "Boxing": {},
        "College Sports": {},
        "Fantasy Sports": {},
        "Football": {},
        "Golf": {},
        "Martial Arts": {
          "Boxing": {},
          "Fighting Games": {},
        },
        "Soccer": {},
        "Sporting Events": {},
        "Sports": {},
        "Tennis": {},
      },
    },
    "Travel & Transportation": {
      "Travel": {
        "Hotels": {},
        "Luggage": {
          "Backpacks": {},
        },
        "Tourism": {
          "Vacation": {},
        },
        "Travel": {},
        "Travel Planning": {
          "Maps": {},
          "Ticketing": {},
        },
      },
      "Transportation": {
        "Automotive": {
          "Cars": {},
          "Electric Cars": {},
          "Motorcycles": {},
        },
        "Navigation": {
          "GPS": {},
          "Maps": {},
        },
        "Public Transport": {
          "Ridesharing": {},
        },
        "Transportation": {},
        "Travel Planning": {
          "Maps": {},
          "Ticketing": {},
        },
      },
    },
  },
};

const topicsLinear = [
  "3D Printer",
  "Accessories",
  "Accounting",
  "Action Games",
  "Ad Blockers",
  "Adult Coloring Books",
  "Adventure Games",
  "Advertising",
  "Affiliate marketing",
  "Alarms",
  "Alcohol",
  "Alexa Skills",
  "Amazon",
  "Analytics",
  "Android",
  "Animation",
  "Anonymous",
  "API",
  "Apple",
  "Apple TV",
  "Apple Vision Pro",
  "Apple Watch",
  "Appliances",
  "Aquarium",
  "ARKit",
  "Art",
  "Art Books",
  "Artificial Intelligence",
  "Audio",
  "Augmented Reality",
  "Babies",
  "Backpacks",
  "Banking",
  "Baseball",
  "Basketball",
  "Batteries",
  "Beauty",
  "Biking",
  "Biohacking",
  "Bitcoin",
  "Blockchain",
  "Board Games",
  "Books",
  "Bots",
  "Boxing",
  "Branding",
  "Browser Extensions",
  "Budgeting",
  "Business",
  "Business Books",
  "Business Intelligence",
  "Business Travel",
  "Calendar",
  "Calligraphy",
  "Camping",
  "Cannabis",
  "Card Games",
  "Career",
  "Cars",
  "Cats",
  "Celebrities",
  "Cell Phone",
  "Change Management",
  "Chat rooms",
  "Chrome Extensions",
  "Classical Music",
  "Climate Tech",
  "Climbing",
  "Clothing",
  "Coding Books",
  "Coffee",
  "College Sports",
  "Coloring",
  "Comedy",
  "Community",
  "Computers",
  "Concert",
  "Concerts",
  "Construction",
  "Consulting",
  "Cookbooks",
  "Cooking",
  "Cosmetics",
  "Couples",
  "Crafting",
  "Crafting Games",
  "Credit card",
  "Crime Books",
  "CRM",
  "Crowdfunding",
  "Crypto",
  "Cryptocurrency",
  "Customer Communication",
  "Customer Success",
  "Custom Keyboards",
  "DAO",
  "DApp",
  "Data",
  "Database",
  "Data Science",
  "Data Visualization",
  "Dating",
  "DeFi",
  "Delivery",
  "Design",
  "Design Books",
  "Design resources",
  "Design templates",
  "Design Tools",
  "Developer Tools",
  "Development",
  "Development Language",
  "Dieting",
  "Digital Art",
  "Dining",
  "DIY",
  "DJing",
  "DJ Khaled",
  "Dogs",
  "Donald Trump",
  "Drake",
  "Drawing",
  "Drinking",
  "Driving Games",
  "Drones",
  "DSLRs",
  "eBook Reader",
  "Edge Extensions",
  "Education",
  "Electric Cars",
  "Electronic Music",
  "Email",
  "Email Marketing",
  "Emoji",
  "Emulators",
  "Encryption",
  "Entertainment",
  "Ethereum",
  "Event marketing",
  "Events",
  "Extended Reality",
  "Facebook Messenger",
  "Family",
  "Fantasy Games",
  "Farming",
  "Fashion",
  "Fashion Books",
  "FemTech",
  "Fighting Games",
  "Finance",
  "Fintech",
  "First Person Shooter",
  "Fitness",
  "Food Delivery",
  "Football",
  "Free Games",
  "Freelance",
  "Fundraising",
  "Funny",
  "Funny Games",
  "Furniture",
  "Games",
  "Gear VR",
  "GIFs",
  "GitHub",
  "Global Nomad",
  "Golf",
  "GPS",
  "Graphic Design",
  "Graphics",
  "Growth Hacking",
  "Growth Hacks",
  "Hacking",
  "Hardware",
  "Health",
  "Health news",
  "Hiking",
  "Hiring",
  "Historical Games",
  "History Books",
  "Home",
  "Home Automation",
  "Home improvement",
  "Home office",
  "Home security",
  "Home services",
  "Home theater",
  "Horror Books",
  "Horror Games",
  "Hotels",
  "HTC Vive",
  "Human Resources",
  "Icons",
  "Illustration",
  "iMessage Apps",
  "Inclusivity",
  "Indie Games",
  "Influencer marketing",
  "Instagram",
  "Interior design",
  "Internet of Things",
  "Intimacy",
  "Investing",
  "iOS",
  "iPad",
  "Isometric Games",
  "Jewelry",
  "Kanye West",
  "Kids",
  "Languages",
  "Legal",
  "Lifestyle",
  "LinkedIn",
  "Linux",
  "Live Events",
  "Live Music",
  "Local news",
  "Logo Design",
  "Mac",
  "Maker Tools",
  "Maps",
  "Marketing",
  "Marketing attribution",
  "Marketing automation",
  "Marketing calendar",
  "Medical",
  "Meditation",
  "Medium",
  "Meetings",
  "Memes",
  "Menu Bar Apps",
  "Messaging",
  "Military",
  "Mixed Reality",
  "MMOs",
  "Modeling",
  "Monetization",
  "Money",
  "Motorcycles",
  "Movies",
  "Music",
  "Nature",
  "Neighborhood",
  "News",
  "Newsletters",
  "NFT",
  "Nintendo",
  "Notes",
  "Notion",
  "Novels",
  "Nutrition",
  "Oculus Rift",
  "Online Learning",
  "Open Source",
  "Open World Games",
  "Operations",
  "Outdoors",
  "Painting",
  "Parenting",
  "Party",
  "Password manager",
  "Payments",
  "PC",
  "Personal Finance",
  "Personal shopper",
  "Pets",
  "Photo editing",
  "Photography",
  "Photoshop",
  "Physics",
  "Plants",
  "Platformers",
  "Playstation",
  "PlayStation VR",
  "Pokemon",
  "Political news",
  "Politics",
  "Pop culture",
  "Pregnancy",
  "Printing",
  "Privacy",
  "Product Hunt",
  "Productivity",
  "Prototyping",
  "Psychedelics",
  "Public Relations",
  "Puzzle Games",
  "Quantified Self",
  "Racing",
  "Radio",
  "reddit",
  "Remote Work",
  "Retro Games",
  "Ridesharing",
  "Robots",
  "RPGs",
  "Running",
  "SaaS",
  "Safari Extensions",
  "Sales",
  "School",
  "Science",
  "Science Books",
  "SDK",
  "Search",
  "Security",
  "Sensors",
  "SEO",
  "Shopping",
  "Side Project",
  "Simulation Games",
  "Skateboarding",
  "Sketch",
  "Slack",
  "Snapchat",
  "Snow sports",
  "Soccer",
  "Social Impact",
  "Social Media",
  "Social media marketing",
  "Social Network",
  "Social Networking",
  "Software Engineering",
  "SoundCloud",
  "Space",
  "Spirituality",
  "Sporting Events",
  "Sports",
  "Sports Games",
  "Spotify",
  "Spreadsheets",
  "Standing Desks",
  "Startup Books",
  "Startup Lessons",
  "Star Wars",
  "Statistical Analysis",
  "Storage",
  "Strategy Games",
  "Streaming Services",
  "Streetwear",
  "Surfing",
  "Survival",
  "Swimming",
  "Tablet",
  "Tabletop Games",
  "Task Management",
  "Tech",
  "Tech news",
  "Telegram",
  "Tennis",
  "Textbooks",
  "Text Editors",
  "Theater",
  "Thriller Books",
  "Ticketing",
  "Time Tracking",
  "Toddlers",
  "Touch Bar Apps",
  "Tower Defense Games",
  "Toys",
  "Transportation",
  "Travel",
  "Tuning",
  "TV",
  "Twitter",
  "Typography",
  "User Experience",
  "UX Design",
  "Vacation",
  "Venture Capital",
  "Video",
  "Video Art",
  "Video cameras",
  "Video Streaming",
  "Virtual Assistants",
  "Virtual Reality",
  "Vita",
  "VPN",
  "Wallpaper",
  "Wearables",
  "Weather",
  "Web3",
  "Web App",
  "Webcam",
  "Web Design",
  "Website Builder",
  "Weightlifting",
  "Wii U",
  "Windows",
  "Wine",
  "Wireframing",
  "Word Games",
  "WordPress",
  "Work In Progress",
  "Writing",
  "XBox",
  "Yoga Books",
  "YouTube",
  "Zombie Games",
  "Arts & Culture",
  "Visual Arts",
  "Performing Arts",
  "Opera",
  "Literature",
  "Business & Entrepreneurship",
  "Business Operations",
  "Marketing & Advertising",
  "Entrepreneurship",
  "Computing & Technology",
  "Software",
  "Web Technology",
  "Data & Analytics",
  "Security & Privacy",
  "Emerging Technologies",
  "Design & Creative Work",
  "Creative Work",
  "Education & Careers",
  "Careers",
  "Finance & Money",
  "Food & Beverages",
  "Food",
  "Beverages",
  "Games & Entertainment",
  "Video Games",
  "Board & Card Games",
  "Health & Fitness",
  "Home & Family",
  "Hobbies & Interests",
  "Hobbies",
  "Gardening & Plants",
  "Interests",
  "News & Media",
  "Media",
  "Blogs",
  "Multimedia",
  "Podcasts",
  "Podcasts",
  "Discord",
  "Streaming",
  "Office & Productivity",
  "Office Software",
  "Notifications",
  "Work Tools",
  "Business Tools",
  "Collaboration",
  "File Sharing",
  "Project Management",
  "Office Setup",
  "Work Trends",
  "Digital Nomads",
  "Retail",
  "Coupons",
  "Sports & Outdoors",
  "Gardening & Plants",
  "Fantasy Sports",
  "Martial Arts",
  "Travel & Transportation",
  "Luggage",
  "Tourism",
  "Travel Planning",
  "Automotive",
  "Navigation",
  "Public Transport",
  "Travel Planning",
];
