import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { ReCaptchaProvider } from "next-recaptcha-v3";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReCaptchaProvider
          useEnterprise
          reCaptchaKey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        >
          {children}
          <Toaster />
        </ReCaptchaProvider>
      </body>
    </html>
  );
}
